# Generated by Django 4.2.4 on 2023-08-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
