# Generated by Django 4.2.4 on 2023-08-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('word_0', models.CharField(default='', max_length=100)),
                ('word_1', models.CharField(default='', max_length=100)),
                ('word_2', models.CharField(default='', max_length=100)),
                ('public', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(default='1970-01-01', verbose_name='date published')),
            ],
        ),
    ]
