# Generated by Django 4.2.4 on 2023-08-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='words',
        ),
        migrations.AddField(
            model_name='theme',
            name='words_0',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='theme',
            name='words_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='theme',
            name='words_2',
            field=models.TextField(default=''),
        ),
    ]
