# Generated by Django 4.2.4 on 2023-08-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_remove_theme_words_theme_words_0_theme_words_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='words_0',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='theme',
            name='words_1',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='theme',
            name='words_2',
            field=models.TextField(default='', max_length=100),
        ),
    ]
