# Generated by Django 4.2.4 on 2023-08-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_alter_theme_words_0_alter_theme_words_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='words_0',
            new_name='word_0',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='words_1',
            new_name='word_1',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='words_2',
            new_name='word_2',
        ),
    ]
