# Generated by Django 4.2.4 on 2023-08-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_rename_words_0_theme_word_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='pub_date',
            field=models.DateTimeField(default=0, verbose_name='date published'),
        ),
    ]
