# Generated by Django 4.2.4 on 2023-08-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(default='1970-01-01'),
        ),
    ]
