# Generated by Django 4.2.4 on 2023-08-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_image_likes_alter_image_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='object',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
