# Generated by Django 4.2.4 on 2023-08-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_image_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
